name: pezshkyar
description: "A new Flutter project."

version: 1.1.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.7
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  intl: ^0.20.2
  flutter_local_notifications: any
  persian_datetime_picker: ^2.6.0
  shamsi_date: ^1.0.1
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  package_info_plus : any
  flutter_markdown: any
  image_picker : any
  shimmer: any
  frosted_glass: any
  dio : any
  jiffy : any
  glassmorphism: ^3.0.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  linux:
    generate: true
  macos:
    generate: true
  windows:
    generate: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/




