name: Flutter Multi-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-ios-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Ensure macOS runner
        run: flutter create --platforms=macos .

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

      - name: Build macOS
        run: flutter build macos --release

      - name: Upload Artifacts (Android/iOS/macOS)
        uses: actions/upload-artifact@v4
        with:
          name: android-ios-macos
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/ios/ipa/*.ipa
            build/macos/Build/Products/Release/**

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Ensure Windows runner
        run: flutter create --platforms=windows .

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows/runner/Release/**

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Ensure Linux runner
        run: flutter create --platforms=linux .

      - name: Build Linux
        run: flutter build linux --release

      - name: Upload Artifacts (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux/x64/release/bundle/**
