name: Flutter Multi-Platform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter/setup-flutter@v2
        with:
          channel: stable
          flutter-version: '3.32.8'
      - run: flutter pub get

      - name: Build Android Debug
        run: flutter build apk --debug
      - name: Build Android Release
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/*.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter/setup-flutter@v2
        with:
          channel: stable
          flutter-version: '3.32.8'
      - run: flutter pub get

      - name: Build iOS Debug (no codesign)
        run: flutter build ios --debug --no-codesign
      - name: Build iOS Release (no codesign)
        run: flutter build ipa --release --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: ios-builds
          path: build/ios/**/**/*.{ipa,app}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter/setup-flutter@v2
        with:
          channel: stable
          flutter-version: '3.32.8'
      - run: flutter pub get

      - name: Build Windows Debug
        run: flutter build windows --debug
      - name: Build Windows Release
        run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: build/windows/runner/**

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter/setup-flutter@v2
        with:
          channel: stable
          flutter-version: '3.32.8'
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev libblkid-dev
      - run: flutter pub get

      - name: Build Linux Debug
        run: flutter build linux --debug
      - name: Build Linux Release
        run: flutter build linux --release

      - uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: build/linux/x64/release/bundle/**

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter/setup-flutter@v2
        with:
          channel: stable
          flutter-version: '3.32.8'
      - run: flutter pub get

      - name: Build macOS Debug (no codesign)
        run: flutter build macos --debug --no-codesign
      - name: Build macOS Release (no codesign)
        run: flutter build macos --release --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: macos-builds
          path: build/macos/Build/Products/**/ 
