name: Flutter Multi-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-all:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Flutter Pub Get
        run: flutter pub get

      # بازسازی پوشه های Linux/MacOS در صورت نبودن
      - name: Ensure Platform Runners
        run: |
          if [ ! -d "linux" ]; then
            flutter create .
          fi
          if [ ! -d "macos" ]; then
            flutter create .
          fi

      # Build Android
      - name: Build Android APK
        run: flutter build apk --release

      # Build iOS
      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

      # Build Windows
      - name: Build Windows
        run: flutter build windows --release

      # Build Linux
      - name: Build Linux
        run: flutter build linux --release

      # Build macOS
      - name: Build macOS
        run: flutter build macos --release

      # Upload all artifacts
      - name: Upload all build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-all
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/ios/ipa/**/*.ipa
            build/ios/ipa/**/*.xcarchive
            build/windows/runner/Release/**
            build/linux/x64/release/bundle/**
            build/macos/Build/Products/Release/**
